apiVersion: v1
kind: ReplicationController
metadata:
  name: app-name-0.0.0
spec:
  replicas: 1
  selector:
    app: app-name
    version: 0.0.0
  template:
    metadata:
      labels:
        app: app-name
        version: 0.0.0
        scope: gennion
    spec:
      containers:
        - resources:
          image: eu.gcr.io/optimal-life-112611/app-name:0.0.0
          imagePullPolicy: Always
          name: app-name
          ports:
            - containerPort: 80
              name: http
